name: fvtools
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - affine=2.4.0
  - asttokens=2.2.1
  - attrs=23.1.0
  - backcall=0.2.0
  - certifi=2022.12.7
  - cftime=1.6.2
  - charset-normalizer=3.1.0
  - click=8.1.3
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cmocean=3.0.3
  - contextily=1.3.0
  - contourpy=1.0.7
  - cycler=0.11.0
  - decorator=5.1.1
  - executing=1.2.0
  - f90nml=1.4.3
  - fiona=1.9.3
  - fonttools=4.39.3
  - geopandas=0.12.2
  - geopy=2.3.0
  - idna=3.4
  - ipython=8.13.2
  - jedi=0.18.2
  - joblib=1.2.0
  - kiwisolver=1.4.4
  - llvmlite=0.40.0
  - lxml=4.9.2
  - matplotlib=3.7.1
  - matplotlib-inline=0.1.6
  - mercantile=1.2.1
  - munch=2.5.0
  - networkx=3.1
  - owslib=0.29.1
  - packaging=23.1
  - pandas=2.0.1
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.5.0
  - progressbar=2.5
  - prompt-toolkit=3.0.38
  - ptyprocess=0.7.0
  - pygments=2.15.1
  - pyparsing=3.0.9
  - pyproj=3.5.0
  - pyshp=2.3.1
  - python-dateutil=2.8.2
  - pytz=2023.3
  - pyyaml=6.0
  - rasterio=1.3.6
  - requests=2.29.0
  - scipy=1.10.1
  - seawater=3.3.4
  - setuptools-scm=7.1.0
  - six=1.16.0
  - snuggs=1.4.7
  - traitlets=5.9.0
  - typing_extensions=4.5.0
  - urllib3=1.26.15
  - utm=0.7.0
  - wcwidth=0.2.6
  - xarray=2023.4.2
  - xyzservices=2023.2.0
  - chardet=5.1.0
  - pip
  - pip:
    - pyTM
    - pure-eval
    - stack-data
